### ISSUE TITLE
Can't update the startValues dynamically 

### ISSUE THREAD

**Issue by moisespio** [albert-gonzalez/easytimer-react-hook#1]
I have a scenario where I want the user to be able to control the startValues and I'm having trouble with it. I'm using the state to set the startValues but the values are not updated when the state is updated.

```javascript
const [timerMinutes, setTimerMinutes] = React.useState('0');
const [timerSeconds, setTimerSeconds] = React.useState('20');

const [timer, isTimerAchieved] = useTimer({
    countdown: true,
    precision: 'secondTenths',
    startValues: { minutes: timerMinutes, seconds: timerSeconds }
});

//I was hoping that calling this function would update the startValues to 1:30 for the instance.
function udpateTimer() {
    setTimerMinutes(1)
    setTimerSeconds(30)
}
```

Am I doing something wrong? What is the best way to achieve that?
Here's an example: https://codesandbox.io/s/broken-violet-hw5mw?file=/src/App.js

**Comment by albert-gonzalez** [comment]
Hi!

Sorry for the late response, I totally missed this issue :(. I am going to answer you anyway, maybe it can help you or other users. useTimer creates a single timer, once it is created you can't create it again with other values. If you need to change the configuration, you need to call timer.start({ /* new config here*/}). I updated your example with a fix: https://codesandbox.io/s/vigorous-poitras-2s7jr?file=/src/App.js

Notice that the timer needs to be stopped to be started again with the new values.

Best regards!
